from ui.login import FrmLogin
from ui.main import FrmMain
from ui.book_category import FrmBookCategoryManage
from ui.book_manage import FrmBookManage
from ui.reader_category import FrmReaderCategoryManage
from ui.reader_manage import FrmReaderManage
from ui.borrow_book import FrmBorrowBook
from ui.return_book import FrmReturnBook
from ui.borrow_record import FrmBorrowRecord